# Generated by Django 3.0.5 on 2020-04-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imdb_id", models.CharField(max_length=50, verbose_name="imdb id")),
                (
                    "title",
                    models.CharField(max_length=255, unique=True, verbose_name="title"),
                ),
                ("plot", models.TextField(blank=True, verbose_name="plot")),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="year"
                    ),
                ),
                (
                    "runtime",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="runtime"
                    ),
                ),
                (
                    "released",
                    models.DateField(blank=True, null=True, verbose_name="released"),
                ),
                ("dvd", models.DateField(blank=True, null=True, verbose_name="dvd")),
                (
                    "pg_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("G", "G"),
                            ("PG", "PG"),
                            ("PG-13", "PG-13"),
                            ("R", "R"),
                            ("NC-17", "NC-17"),
                        ],
                        max_length=10,
                        verbose_name="pg rating",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=2, null=True, verbose_name="rating"
                    ),
                ),
                (
                    "genre",
                    models.CharField(blank=True, max_length=100, verbose_name="genre"),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="language"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "director",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="director"
                    ),
                ),
                ("writer", models.TextField(blank=True, verbose_name="writer")),
                (
                    "actors",
                    models.CharField(blank=True, max_length=255, verbose_name="actors"),
                ),
                (
                    "awards",
                    models.CharField(blank=True, max_length=255, verbose_name="awards"),
                ),
                (
                    "poster",
                    models.URLField(blank=True, max_length=255, verbose_name="poster"),
                ),
                (
                    "production",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="production"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
        )
    ]
