# Generated by Django 3.0.5 on 2020-04-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("movies", "0002_comment")]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
            preserve_default=False,
        )
    ]
